### ISSUE TITLE
Error while running pca demo in neurocaas

### ISSUE THREAD

**Issue by anjaliagarwal8** [cunningham-lab/neurocaas_contrib#31]
When I run the command neurocaas-contrib workflow log-command-local -c ./run_pca.sh for getting the results of pca, I am getting the following error

Error getting NeuroCAASDataStatusLegacy object, not connecting to remote. Loading default NeuroCAASDataStatusLegacy template from local instead.
Error getting NeuroCAASCertificate object, not connecting to remote. Loading default NeuroCAASCertificate template from local instead.
No file to reload from, returning current.
Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\Scripts\neurocaas-contrib.exe\__main__.py", line 7, in <module>
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\neurocaas_contrib\main.py", line 5, in main
    cli()
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\neurocaas_contrib\cli_commands.py", line 1183, in log_command_local
    ncsm.log_command(command,"s3://nonexistent/file",resultpath)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\neurocaas_contrib\scripting.py", line 527, in log_command
    log_process(command,os.path.join(path,"log.txt"),s3log)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\site-packages\neurocaas_contrib\scripting.py", line 99, in log_process
    process = subprocess.Popen(command,stdout = writer,stderr = writer)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Acer\anaconda3\envs\neurocaas\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Does anybody know how to resolve this?
Thank you

**Comment by cellistigs** [comment]
It looks like this is an issue in how subprocess works across different operating systems ( https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application). I'll work on a fix for this, and ask you to try again as soon as we have something. Thank you!

**Comment by anjaliagarwal8** [comment]
Thank you for the info, I was able to run it on a Linux machine so I guess it is an OS issue. I'll be happy to check it out again once the issue is fixed.
